update zh_cn.json
ChefMooon/frights-delight pull request #8
Opened 2024-09-21 11:38 UTC by Ianzb

Some Chinese translations is bad or outdated, so I updated some of them.

2024-11-09 03:36 UTC, QiuShui1012 requested changes

2024-11-09 03:36 UTC, QiuShui1012 commented on src/main/resources/assets/frightsdelight/lang/zh_cn.json
>    "frightsdelight.effect.chills.start": "你感到空气正在变得寒冷...",
标点符号需使用全角符号，...（英文三个点）应改为…（中文三点符号）

2024-11-12 19:44 UTC, ChefMooon commented
Appreciate you guys collaborating on the update to the translations. They will be included in the next release!

2024-11-12 19:45 UTC, ChefMooon approved these changes

2024-11-12 19:45 UTC, merged